### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by fo5** [Ideea-Technologies/Spectre#1]
The README should specify the origin of the code.

`Published by Ideea Technologies LTD` is misleading.

See appendix A of https://spectreattack.com/spectre.pdf

**Comment by anthonybudd** [comment]
It's not misleading because it clearly says "published by" and not "Written by" or "Created by". Just like a publisher that publishes a book, nobody had ever assumed Simon & Schuster is the author...

Nonetheless:
https://github.com/Ideea-Technologies/Spectre/commit/e314f8c6eb503f156c8193074c9b2477fb195b0b
